### ISSUE TITLE
Crash on startup when Sounds folder is empty

### ISSUE THREAD

**Issue by xmbhasin** [bryanbarcos/TalkBox-Pro#2]
**Description**: The ConfigurationApp.jar crashes on startup when the Sounds folder is empty.

**Steps to Reproduce:** 
1. Place the ConfigurationApp.jar in an empty directory. 
2. Create an empty Sounds directory beside the ConfigurationApp.jar.
3. Launch the ConfigurationApp.jar from the command line.

**Expected Results:** Configuration App should launch with an initially empty list of audio files.

**Actual Results:** Configuration App crashes with the following stack trace:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at TalkBoxConfigurationGUI.ConfigurationAppGUI.makeFrame(ConfigurationAppGUI.java:369)
        at TalkBoxConfigurationGUI.ConfigurationAppGUI.<init>(ConfigurationAppGUI.java:104)
        at TalkBoxConfigurationGUI.ConfigurationAppGUI.main(ConfigurationAppGUI.java:67)
```

**Product Version:** Midterm Release (tag `vM`)

**OS:**
```
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17134.0 Microsoft Windows NT 10.0.17134.0
```
**Java Version:**
```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by bryanbarcos** [comment]
Updated ConfigurationAppGUI class. Added statement to check if sounds folder is empty. 
Issue Resolved.
