### ISSUE TITLE
Application Launch Bug

### ISSUE THREAD

**Issue by mdanialqureshi** [bryanbarcos/TalkBox-Pro#3]
**Group Number 14 Bug Report**
 
**Description:** 

Upon launch on macOS, the following frame appears:

![image](https://user-images.githubusercontent.com/43326215/54134180-dae10180-43ed-11e9-8e5a-500279509882.png)

This may be a cross platform problem, as the message shows “.\”, which is a windows directory character. e.g macOS is “/”.  

**Steps to Reproduce:** 

1.	Place configuration app in a shared directory with the “Sounds” directory. 
2.	Try to launch the configuration app by double clicking the application or launching in terminal with “java -jar ConfigurationApp.jar"
3.	The respective error frame should be visible. 

**Actual vs Expected Results:** 

Actual: Application does not launch; error frame is shown.

Expected: Application launches properly. 

**Stacktrace:** 
```
Exception in thread "main" java.lang.NullPointerException
	at TalkBoxConfigurationGUI.ConfigurationAppGUI.makeFrame(ConfigurationAppGUI.java:252)
	at TalkBoxConfigurationGUI.ConfigurationAppGUI.<init>(ConfigurationAppGUI.java:104)
	at TalkBoxConfigurationGUI.ConfigurationAppGUI.main(ConfigurationAppGUI.java:67)

```

**OS:** 

System Software Overview:
      System Version: macOS 10.14.3 (18D109)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

**Java Version:** 

```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by Dhruv9979** [comment]
Changed the format for searching sound directory. 
Now works on all OS.
Issue Resolved
