### ISSUE TITLE
Unable to open ConfigurationApp.jar

### ISSUE THREAD

**Issue by leungj73** [bryanbarcos/TalkBox-Pro#4]
**Description:** Unable to open ConfigurationApp.jar, produces error code: ".\Sounds must be a directory."

**Product Version:** TalkBox-Pro-master

**Steps to Reproduce:**
1. Download and unzip TalkBox-Pro-master.zip
2. Put TalkBox-Pro-master folder in a directory (including both existing ConfigurationApp.jar and Sounds folder)
3. Open ConfigurationApp.jar using Jar Launcher

**Expected Results:** TalkBox Configuration App opens. 

**Actual Results:** Error code popup: ".\Sounds must be a directory." ConfigurationApp does not open after the "OK" button is clicked 

**OS:**
`ProductName:	Mac OS X`
`ProductVersion:	10.14`
`BuildVersion:	18A391` 

**Java Version**
`java version "11.0.2" 2019-01-15 LTS`
`Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)`
`Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)`

**Comment by paramganeshan** [comment]
To fix this issue, the icons and Sounds directories were copied to the C:\Users\param\git\TalkBox-Pro\build\libs path. Now the jar file runs as expected.
